### ISSUE TITLE
How can I handle uuid and jsob in PGSQL

### ISSUE THREAD

**Issue by hasanAjsf** [piever/JuliaDBTutorial#2]
In my database, I've the below structure:
```sql
CREATE TABLE public.devices
(
    id uuid,
    data jsonb
)
```
When I run my query using this package, I got the below, how can I read the output properly?

![image](https://user-images.githubusercontent.com/46838626/64477805-8eae2880-d1a8-11e9-923f-2518c477cd68.png)

**Comment by piever** [comment]
This is just a repo containing a tutorial, the issue section here is not really meant for usage questions. Please use the [JuliaDB](https://github.com/JuliaComputing/JuliaDB.jl) repository to report bugs and the discourse forum or slack channel JuliaDB for usage question (see [here](https://julialang.org/community/) for a list of online Julia communities).
